on: [push]
jobs:
    Backend-Client-Functional-Tests-CI:
        runs-on: ubuntu-20.04
        steps:
            - name: Check out the commit that triggered this job
              uses: actions/checkout@v3
              with:
                path: ${{ github.event.repository.name }}

            - name: launch container
              run: |
                  cd nopayloaddb/
                  docker-compose up --build -d
                  sleep 30

            - name: wait for container
              uses: ifaxity/wait-on-action
              with:
                  resource: http://localhost:8000/api/cdb_rest/globalTags

            - name: Check out client-side repository
              uses: actions/checkout@v3
              with:
                  repository: ligerlac/nopayloadclient
                  token: ${{ secrets.my_token }}

            - name: test curl
              run: curl http://localhost:8000/api/cdb_rest/gt
