on: [push]
jobs:
    Backend-Client-Functional-Tests-CI:
        runs-on: ubuntu-20.04
        steps:
            - name: print working dir
              run: pwd

            - name: Check out the commit that triggered this job
              uses: actions/checkout@v3
              with:
                path: ${{ github.event.repository.name }}

            - name: launch container
              run: |
                  cd nopayloaddb/
                  docker-compose up --build -d
                  sleep 30

            - name: print working dir
              run: pwd

            - name: Check out client-side repository
              uses: actions/checkout@v3
              with:
                  repository: ligerlac/nopayloadclient
                  token: ${{ secrets.my_token }}

            - name: Run client-side tests
              run: |
                  cd nopayloadclient
                  cmake -DBUILD_TESTING=ON -S . -B build
                  cmake --build build/
                  cd build/
                  ctest --verbose

            - name: test curl
              run: curl http://localhost:8000/api/cdb_rest/gt
