on: [push]
jobs:
    Backend-Client-Functional-Tests-CI:
        runs-on: ubuntu-20.04
        steps:
            - name: Setup SSH Keys and known_hosts
              env:
                  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
              run: |
                  echo "test 1"
                  mkdir -p ~/.ssh
                  echo "test 2"
                  ssh-keyscan github.com >> ~/.ssh/known_hosts
                  echo "test 3"
                  ssh-agent -a $SSH_AUTH_SOCK > /dev/null
                  echo "test 4"
                  ssh-add - <<< "${{ secrets.DEPLOY_KEY }}"

            - name: Check out the commit that triggered this job
              uses: actions/checkout@v3
              with:
                path: ${{ github.event.repository.name }}

            - name: launch container
              run: docker-compose up --build -d

            - name: test curl
              run: curl http://localhost:8000/api/cdb_rest/gt
