name: Django CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: dbname
          POSTGRES_USER: login
          POSTGRES_PASSWORD: password

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
        with:
          path: nopayloaddb
      - name: Install Dependencies
        run: |
          cd nopayloaddb/
          pip install -r requirements.txt
      - name: Change permissions of /var/log/
        run: sudo chmod a+w /var/log/
      - name: Wait for PostgreSQL to become ready
        run: until pg_isready -h localhost -p 5432; do sleep 2; done
      - name: Run Django
        env:
          POSTGRES_DB: dbname
          POSTGRES_USER: login
          POSTGRES_PASSWORD: password
        run: |
          cd nopayloaddb/
          python manage.py makemigrations cdb_rest && python manage.py migrate && python manage.py runserver 0.0.0.0:8000
