name: Django CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: dbname
          POSTGRES_USER: login
          POSTGRES_PASSWORD: password
          POSTGRES_HOST: db
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      npdb:
        build: .
        env:
          POSTGRES_DB: dbname
          POSTGRES_USER: login
          POSTGRES_PASSWORD: password
          POSTGRES_HOST: db
          POSTGRES_PORT: 5432
        depends_on:
          db:
            condition: service_healthy
        ports:
          - 8000:8000

    steps:
      - name: Run Django
        run: |
            python manage.py makemigrations cdb_rest
            python manage.py migrate
            python manage.py runserver 0.0.0.0:8000