name: Django CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

  services:
    db:
      image: postgres
      env:
        POSTGRES_DB: dbname
        POSTGRES_USER: login
        POSTGRES_PASSWORD: password
        POSTGRES_HOST: db
        POSTGRES_PORT: 5432

  steps:
    - name: Check out the commit that triggered this job
      uses: actions/checkout@v3
    - name: launch container
      run: |
        cd nopayloaddb/
        python manage.py makemigrations cdb_rest && python manage.py migrate && python manage.py runserver 0.0.0.0:8000
