name: Django CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env_file: .env

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      npdb:
        build: .
        entrypoint: [ "/bin/sh", "-c" ]
        command:
          - |
            python manage.py makemigrations cdb_rest
            python manage.py migrate
            python manage.py runserver 0.0.0.0:8000
        ports:
          - 8000:8000
        restart: always
        depends_on:
          db:
            condition: service_healthy
        env_file: .env